name: dem_pg

dependencies:
  - clangxx==10
  - libcxx==10
  - llvm-openmp==10
  - clang-tools==10
  - "cmake>=3.8"
  - fmt>=8.0.0

environment:
  LIBRARY_PATH:
    - $CONDA_PREFIX/lib
    - $LIBRARY_PATH
  LD_LIBRARY_PATH:
    - $CONDA_PREFIX/lib
    - $LD_LIBRARY_PATH